---
- hosts: big_ips
  tasks:
    - name: Create and Download a new UCS
      bigip_ucs_fetch:
        src: "{{ backup_file }}"
        dest: "{{ local_path }}{{ backup_file }}"
        create_on_missing: yes
        provider: "{{ bigip_provider }}"
      delegate_to: localhost

    - name: Remove created UCS file
      bigip_ucs:
        ucs: "{{ backup_file }}"
        state: absent
        provider: "{{ bigip_provider }}"
      delegate_to: localhost
