all:
  children:
    big_ips:
      hosts:
        bigip1.example.com:
            ansible_connection: local
            backup_file: my_backup.ucs
            local_path: ./
            bigip_provider:
              server: "{{ inventory_hostname }}"
              user: "admin"
              password: "password"
              validate_certs: false
              server_port: 443
